//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionDAM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowEmisoresSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowEmisoresSize"]));
            }
            set {
                this["BrowEmisoresSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowEmisoresLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowEmisoresLocation"]));
            }
            set {
                this["BrowEmisoresLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Maximized\"")]
        public string BrowEmisoresState {
            get {
                return ((string)(this["BrowEmisoresState"]));
            }
            set {
                this["BrowEmisoresState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowClientesSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowClientesSize"]));
            }
            set {
                this["BrowClientesSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowClientesLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowClientesLocation"]));
            }
            set {
                this["BrowClientesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Maximized\"")]
        public string BrowClientesState {
            get {
                return ((string)(this["BrowClientesState"]));
            }
            set {
                this["BrowClientesState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowConceptosFacSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowConceptosFacSize"]));
            }
            set {
                this["BrowConceptosFacSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowConceptosFacLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowConceptosFacLocation"]));
            }
            set {
                this["BrowConceptosFacLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Maximized\"")]
        public string BrowConceptosFacState {
            get {
                return ((string)(this["BrowConceptosFacState"]));
            }
            set {
                this["BrowConceptosFacState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowTiposIvaSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowTiposIvaSize"]));
            }
            set {
                this["BrowTiposIvaSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowTiposIvaLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowTiposIvaLocation"]));
            }
            set {
                this["BrowTiposIvaLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Maximized\"")]
        public string BrowTiposIvaState {
            get {
                return ((string)(this["BrowTiposIvaState"]));
            }
            set {
                this["BrowTiposIvaState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowProductosSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowProductosSize"]));
            }
            set {
                this["BrowProductosSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowProductosLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowProductosLocation"]));
            }
            set {
                this["BrowProductosLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Maximized\"")]
        public string BrowProductosState {
            get {
                return ((string)(this["BrowProductosState"]));
            }
            set {
                this["BrowProductosState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UltimoAnhoSeleccionado {
            get {
                return ((int)(this["UltimoAnhoSeleccionado"]));
            }
            set {
                this["UltimoAnhoSeleccionado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Maximized\"")]
        public string BrowFacemiState {
            get {
                return ((string)(this["BrowFacemiState"]));
            }
            set {
                this["BrowFacemiState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowFacemiSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowFacemiSize"]));
            }
            set {
                this["BrowFacemiSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowFacemiLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowFacemiLocation"]));
            }
            set {
                this["BrowFacemiLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Normal\"")]
        public string BrowProveedoresState {
            get {
                return ((string)(this["BrowProveedoresState"]));
            }
            set {
                this["BrowProveedoresState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900, 600")]
        public global::System.Drawing.Size BrowProveedoresSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowProveedoresSize"]));
            }
            set {
                this["BrowProveedoresSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowProveedoresLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowProveedoresLocation"]));
            }
            set {
                this["BrowProveedoresLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Maximized\"")]
        public string BrowFacrecState {
            get {
                return ((string)(this["BrowFacrecState"]));
            }
            set {
                this["BrowFacrecState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size BrowFacrecSize {
            get {
                return ((global::System.Drawing.Size)(this["BrowFacrecSize"]));
            }
            set {
                this["BrowFacrecSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point BrowFacrecLocation {
            get {
                return ((global::System.Drawing.Point)(this["BrowFacrecLocation"]));
            }
            set {
                this["BrowFacrecLocation"] = value;
            }
        }
    }
}
